name: WORK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: install
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #run
      - name: run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.ACCESS_PASSWORD }}
          port: 22
          script: |
            pm2 stop app
            pm2 delete app
            echo "stop ..."
            cd /home/nodeServer/app
            git pull
            pnpm install
            pm2 start -n app  npm -- run pro
            echo "running ..."
